controllers:
  account_get:
    path: '/account'
    controller: AccountController:getAccount
    method:
      - GET
  account_create:
    path: '/accounts'
    controller: AccountController:createAccount
    method:
      - POST
  account_update:
    path: '/account'
    controller: AccountController:updateAccount
    method:
      - PATCH

  token_post:
    path: '/token'
    controller: TokenController:getToken
    method:
      - POST

  charities:
    path: '/charities'
    controller: CharityController:getList
    method:
      - GET

  merchants:
    path: '/merchants'
    controller: MerchantController:getMerchants
    method:
      - GET

  merchant_image:
    path: '/merchants/{transaction_id}/image'
    controller: MerchantController:getMerchantImage
    method:
      - GET

  goal_create:
    path: '/goal'
    controller: GoalController:create
    method:
      - POST
  goal_list:
    path: '/goals'
    controller: GoalController:list
    method:
      - GET
  goal_update:
    path: '/goals/{id}'
    controller: GoalController:update
    method:
      - PATCH
  goal_delete:
    path: '/goals/{id}'
    controller: GoalController:delete
    method:
      - DELETE

  home:
    path: '/'
    controller: HelloController:world
    method:
       - GET
  bank:
    path: '/bank'
    controller: HelloController:bank
    method:
    - POST
  bunq:
    path: '/bunq/user'
    controller: BunqController:currentUser
    method:
    - GET