controllers:
  account_create:
    path: '/accounts'
    controller: AccountController:createAccount
    method:
      - POST
  account_update:
    path: '/accounts'
    controller: AccountController:updateAccount
    method:
      - PATCH

  home:
    path: '/'
    controller: HelloController:world
    method:
       - GET
  bunq:
    path: '/bunq/user'
    controller: BunqController:currentUser
    method:
    - GET