controllers:
  account_get:
    path: '/account'
    controller: AccountController:getAccount
    method:
      - GET
  account_create:
    path: '/accounts'
    controller: AccountController:createAccount
    method:
      - POST
  account_update:
    path: '/accounts'
    controller: AccountController:updateAccount
    method:
      - PATCH

  token_post:
    path: '/token'
    controller: TokenController:getToken
    method:
      - POST

  charities:
    path: '/charities'
    controller: CharityController:getList
    method:
      - GET

  merchants:
    path: '/merchants'
    controller: MerchantController:getMerchants
    method:
      - GET

  home:
    path: '/'
    controller: HelloController:world
    method:
       - GET
  bank:
    path: '/bank'
    controller: HelloController:bank
    method:
    - POST
  bunq:
    path: '/bunq/user'
    controller: BunqController:currentUser
    method:
    - GET